name: Enviar e-mail de aniversariantes

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 09:00 UTC
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up GOOGLE_CREDENTIALS_JSON
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          echo "GOOGLE_CREDENTIALS_JSON=$GOOGLE_CREDENTIALS_JSON" >> $GITHUB_ENV
      - name: Debug Google credentials
        run: echo $GOOGLE_CREDENTIALS_JSON
      - name: Run script
        run: python jabuti_niver.py
