name: Enviar e-mail de aniversariantes

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 09:00 UTC
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  enviar_email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      - name: Run script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python seu_script.py  # Nome do seu script Python
