name: Enviar e-mail de aniversariantes

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 09:00 UTC
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Etapa para criar o arquivo de credenciais a partir do segredo no GitHub
      - name: Create credentials file from GitHub Secret
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      # Etapa para rodar o script Python com as credenciais
      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json  # Aponta para o arquivo de credenciais
        run: |
          python jabuti_niver.py

      # Etapa para limpar o arquivo de credenciais após o uso
      - name: Clean up credentials
        run: |
          rm credentials.json
